# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        "cid": "{5c25215d-01a7-4ca7-b0d7-a94931936eaf}",
        "contract_ids": ["@deb.local/firefox-cef-bridge;1"],
        "type": "FirefoxCefBridge",
        "singleton": True,
        "constructor": "mozilla::FirefoxCefBridge::GetSingleton",
        "headers": ["mozilla/FirefoxCefBridge.h"],
        "processes": ProcessSelector.MAIN_PROCESS_ONLY,
    },
    {
        "cid": "{921368d4-54ed-42b7-aa00-ba168284ade4}",
        "contract_ids": ["@deb.local/firefox-cef-command-line;1"],
        "esModule": "resource:///modules/FirefoxCefCommandLine.sys.mjs",
        "constructor": "FirefoxCefCommandLineHandler",
        "categories": {"command-line-handler": "a-firefox-cef"},
        "processes": ProcessSelector.MAIN_PROCESS_ONLY,
    },
    {
        "cid": "{a0530e46-98e6-4a17-8ce8-b446b404912e}",
        "contract_ids": ["@mozilla.org/network/protocol;1?name=deb"],
        "esModule": "resource:///modules/DebProtocolHandler.sys.mjs",
        "constructor": "DebProtocolHandler",
        "protocol_config": {
            "scheme": "deb",
            "flags": [
                "URI_STD",
                "URI_IS_LOCAL_RESOURCE",
                "URI_IS_POTENTIALLY_TRUSTWORTHY",
                "URI_IS_UI_RESOURCE",
            ],
        },
    },
]
