# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        "cid": "{5c25215d-01a7-4ca7-b0d7-a94931936eaf}",
        "contract_ids": ["@dual-engine-browser.local/firefox-cef-bridge;1"],
        "type": "FirefoxCefBridge",
        "singleton": True,
        "constructor": "mozilla::FirefoxCefBridge::GetSingleton",
        "headers": ["mozilla/FirefoxCefBridge.h"],
        "processes": ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
