/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIBaseWindow.idl"

[scriptable, uuid(69e18a45-3b22-4505-a57c-f23d5b272fbc)]
interface nsIFirefoxCefBridge : nsISupports
{
  readonly attribute unsigned long browserId;
  readonly attribute AUTF8String initialUrl;
  readonly attribute unsigned long initialWidth;
  readonly attribute unsigned long initialHeight;

  void runtimeReady();
  void attachWindow(in unsigned long browserId, in nsIBaseWindow baseWindow);
  void browserReady(in unsigned long browserId);
  void addressChanged(in unsigned long browserId, in AUTF8String url);
  void titleChanged(in unsigned long browserId, in AUTF8String title);
  void loadingStateChanged(in unsigned long browserId, in boolean loading);
  void loadError(in unsigned long browserId,
                 in long errorCode,
                 in AUTF8String errorText,
                 in AUTF8String failedUrl);
  void browserCrashed(in unsigned long browserId, in AUTF8String reason);
  void beforeClose(in unsigned long browserId);
};
