/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIBaseWindow.idl"

[scriptable, uuid(4a3d637d-0b04-4cb2-9451-a07421fad8c2)]
interface nsIFirefoxCefBridge : nsISupports
{
  readonly attribute unsigned long browserId;
  readonly attribute AUTF8String initialUrl;
  readonly attribute unsigned long initialWidth;
  readonly attribute unsigned long initialHeight;

  void runtimeReady();
  void prepareDevToolsWindow();
  void cancelDevToolsWindow();
  void attachWindow(in unsigned long browserId, in nsIBaseWindow baseWindow);
  void browserReady(in unsigned long browserId);
  void addressChanged(in unsigned long browserId, in AUTF8String url);
  void titleChanged(in unsigned long browserId, in AUTF8String title);
  void loadingStateChanged(in unsigned long browserId, in boolean loading);
  void fullscreenChanged(in unsigned long browserId, in boolean fullscreen);
  void loadError(in unsigned long browserId,
                 in long errorCode,
                 in AUTF8String errorText,
                 in AUTF8String failedUrl);
  void browserCrashed(in unsigned long browserId, in AUTF8String reason);
  void beforeClose(in unsigned long browserId);
};
